# Generated by Django 5.1.1 on 2024-09-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdowncontent',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
