# Generated by Django 4.2.16 on 2024-10-24 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_alter_tip_downvoted_alter_tip_upvoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime'),
        ),
        migrations.CreateModel(
            name='UpvotedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DownvoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='tip',
            name='downvoted',
            field=models.ManyToManyField(to='ex.downvotemodel'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='upvoted',
            field=models.ManyToManyField(to='ex.upvotedmodel'),
        ),
    ]
