# Generated by Django 5.1.1 on 2024-10-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex00', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ex00_movies',
            new_name='movies',
        ),
    ]
