# Generated by Django 4.2.16 on 2024-11-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0004_userfavoritearticle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavoritearticle',
            unique_together={('user', 'article')},
        ),
    ]
