# Generated by Django 4.2.16 on 2024-11-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0005_alter_userfavoritearticle_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_superuser',
        ),
    ]
