# Generated by Django 5.1.1 on 2024-10-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='ex01_movies',
        ),
    ]
