# Generated by Django 5.1.1 on 2024-09-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex00', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarkdownContent',
        ),
    ]
