# Generated by Django 4.2.16 on 2024-11-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
    ]
