# Generated by Django 5.1.1 on 2024-10-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex00', '0002_rename_ex00_movies_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movies',
        ),
    ]
