# Generated by Django 4.2.16 on 2024-10-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0005_users_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
