# Generated by Django 4.2.16 on 2024-10-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0006_alter_users_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_staff',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
    ]
