# Generated by Django 4.2.16 on 2024-10-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0007_rename_is_staff_users_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('auth_delete_tip', 'can delete tip')]},
        ),
    ]
