# Generated by Django 4.2.16 on 2024-10-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0008_alter_tip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='tip_permission',
            field=models.BooleanField(default=True, verbose_name='tip_permission'),
        ),
    ]
