# Generated by Django 4.2.16 on 2024-10-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0009_tip_tip_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='tip_permission',
        ),
    ]
