# Generated by Django 4.2.16 on 2024-10-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0010_remove_tip_tip_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='permission_tip',
            field=models.BooleanField(default=False),
        ),
    ]
