# Generated by Django 4.2.16 on 2024-10-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0011_users_permission_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='permission_tip',
            field=models.TextField(default='Can_not_delete_tip'),
        ),
    ]
