# Generated by Django 4.2.16 on 2024-10-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0013_users_groups_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='permission_tip',
        ),
    ]
