# Generated by Django 4.2.16 on 2024-10-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0014_remove_users_permission_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
