# Generated by Django 4.2.16 on 2024-10-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_tip'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tip',
            table='tip',
        ),
    ]
