# Generated by Django 4.2.16 on 2024-10-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_alter_tip_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='date',
        ),
    ]
