# Generated by Django 4.2.16 on 2024-10-22 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0004_remove_tip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime'),
        ),
    ]
